### ISSUE TITLE
Metadata Slide-Out

### ISSUE THREAD

**Issue by nathanieldeines** [gri-is/dana#62]
![screen shot 2017-05-11 at 5 46 48 pm](https://cloud.githubusercontent.com/assets/16109511/25977664/d965d21c-3671-11e7-92df-158b9bf9009b.png)
![screen shot 2017-05-11 at 5 49 01 pm](https://cloud.githubusercontent.com/assets/16109511/25977711/340ba458-3672-11e7-89b6-843c749fe454.png)

**Comment by nathanieldeines** [comment]
Assigning to @kristenGRI for review.

**Comment by kristenGRI** [comment]
This is generally working and seems to be pulling the correct information. However, there are a few things that are currently missing:

1. User should be able to close the slide-out by clicking outside of it (in conjunction with being able to use the "X")
2. We are missing the headers for "Scope and Content" and "Arrangement" (Text for arrangement seems to be missing altogether.) See "Detailed Description for Series VII.C: http://dana-qa.getty.edu/#/collections/2011m30/series/2011m30_ref237792_fvd/subseries/2011m30_ref239087_tlx
3. I assuming we will eventually add an animation for the slideout. Making a note of it now since there seems to be some animations in the system but this one does not have one.
