### ISSUE TITLE
Image Metadata

### ISSUE THREAD

**Issue by nathanieldeines** [gri-is/dana#68]
![screen shot 2017-05-23 at 2 33 42 pm](https://cloud.githubusercontent.com/assets/16109511/26380068/3908a24a-3fd1-11e7-9967-c1c6d6943e73.png)

**Comment by nathanieldeines** [comment]
Assigning to @kristenGRI for review.

**Comment by kristenGRI** [comment]
This seems to be be pulling in the correct information, so functionally, it appears to be working. (see links and images at the bottom.)

My only concern right now is placement since the wires are outdated. I assume this is something we should compensate for now since it has changed in the comp phase. Note this will also affect tickets #65 and #67.

Should we at this phase also be concerned with stripping out comas, adding spaces, and generally formating the text for the new display?

http://dana-qa.getty.edu/#/collections/2011m30/objects/2011m30_ref1238_tjb
![series iva_niele toroni](https://user-images.githubusercontent.com/15019503/28383614-98f94624-6c76-11e7-84ee-3e81cb390e1c.png)

http://dana-qa.getty.edu/#/collections/2011m30/objects/2011m30_ref15322_935
![seriesi_painter-poets--poet-painters](https://user-images.githubusercontent.com/15019503/28383623-a3c3d7f4-6c76-11e7-922b-a830fa390821.png)

http://dana-qa.getty.edu/#/collections/2011m30/objects/2011m30_ref236986_s0o
![seriesiiib_artist videodocumentation](https://user-images.githubusercontent.com/15019503/28383627-a82d1fc6-6c76-11e7-9677-52e632cd39a9.png)
